// StylesCardapio.jsx
export function getStylesCardapio({ isMobile, isTablet, showFilters }) {
  return {
    container: {
      backgroundColor: "#F8FAFC",
      minHeight: "100vh",
      fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
      maxWidth: isMobile ? "100%" : isTablet ? "768px" : "1200px",
      margin: "0 auto",
    },

    header: {
      background: "linear-gradient(135deg, #0F3460 0%, #1E40AF 100%)",
      padding: isMobile ? "16px" : "20px 24px",
      position: "sticky",
      top: 0,
      zIndex: 100,
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottomLeftRadius: "24px",
      borderBottomRightRadius: "24px",
      boxShadow: "0 4px 20px rgba(15, 52, 96, 0.15)",
    },

    backButton: {
      background: "rgba(255,255,255,0.15)",
      border: "1px solid rgba(255,255,255,0.3)",
      borderRadius: "12px",
      padding: "10px",
      color: "white",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: "8px",
      fontWeight: "700",
      fontSize: isMobile ? "14px" : "16px",
      transition: "all 0.2s ease",
    },

    carrinhoButton: {
      background: "rgba(255,255,255,0.15)",
      border: "1px solid rgba(255,255,255,0.3)",
      borderRadius: "12px",
      padding: isMobile ? "10px 14px" : "12px 18px",
      color: "white",
      display: "flex",
      alignItems: "center",
      gap: "8px",
      cursor: "pointer",
      transition: "all 0.2s ease",
      fontWeight: "800",
      fontSize: isMobile ? "14px" : "16px",
      position: "relative",
    },

    carrinhoBadge: {
      position: "absolute",
      top: "-8px",
      right: "-8px",
      backgroundColor: "#EF4444",
      color: "white",
      borderRadius: "50%",
      width: "22px",
      height: "22px",
      fontSize: "12px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: "bold",
      border: "2px solid rgba(15, 52, 96, 1)",
    },

    storeInfo: {
      textAlign: "center",
      padding: isMobile ? "20px 16px" : "24px",
      backgroundColor: "white",
      marginBottom: "10px",
      borderBottom: "1px solid #E2E8F0",
    },
    storeName: {
      fontSize: isMobile ? "24px" : isTablet ? "28px" : "32px",
      fontWeight: "900",
      color: "#0F3460",
      margin: "0 0 12px 0",
    },
    storeBadges: {
      display: "flex",
      justifyContent: "center",
      gap: isMobile ? "10px" : "15px",
      flexWrap: "wrap",
    },
    badge: {
      padding: isMobile ? "6px 12px" : "8px 16px",
      borderRadius: "20px",
      fontSize: isMobile ? "11px" : "12px",
      fontWeight: "800",
      display: "flex",
      alignItems: "center",
      gap: "6px",
    },
    badgeOpen: { backgroundColor: "#D1FAE5", color: "#065F46" },
    badgeRating: { backgroundColor: "#FEF3C7", color: "#92400E" },
    badgeTime: { backgroundColor: "#DBEAFE", color: "#1E40AF" },

    filtrosContainer: {
      padding: isMobile ? "16px" : "20px 24px",
      backgroundColor: "white",
      borderBottom: "1px solid #E2E8F0",
      position: "sticky",
      top: isMobile ? "60px" : "80px",
      zIndex: 90,
    },
    buscaContainer: {
      display: "flex",
      gap: "12px",
      alignItems: "center",
      flexWrap: "wrap",
    },

    searchInput: {
      flex: 1,
      padding: isMobile ? "12px 16px 12px 44px" : "14px 20px 14px 48px",
      borderRadius: "14px",
      border: "2px solid #E2E8F0",
      backgroundColor: "#F8FAFC",
      outline: "none",
      fontSize: isMobile ? "15px" : "16px",
      minWidth: isMobile ? "200px" : "300px",
      fontWeight: "500",
      transition: "all 0.2s ease",
    },

    filterButton: {
      background: "#0F3460",
      border: "none",
      borderRadius: "12px",
      padding: isMobile ? "12px" : "14px",
      color: "white",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      transition: "all 0.2s ease",
    },

    viewToggle: {
      display: "flex",
      background: "#F1F5F9",
      borderRadius: "12px",
      padding: "4px",
      marginLeft: isMobile ? "auto" : "10px",
    },
    viewButton: {
      padding: isMobile ? "8px 12px" : "10px 14px",
      borderRadius: "10px",
      border: "none",
      background: "none",
      cursor: "pointer",
      color: "#64748B",
      display: "flex",
      alignItems: "center",
      gap: "6px",
      fontSize: isMobile ? "12px" : "14px",
    },
    viewButtonAtivo: {
      backgroundColor: "white",
      color: "#0F3460",
      boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    },

    categoriasContainer: {
      display: "flex",
      gap: isMobile ? "12px" : "16px",
      overflowX: "auto",
      padding: isMobile ? "16px" : "20px 24px",
      backgroundColor: "white",
      borderBottom: "1px solid #F1F5F9",
      position: "sticky",
      top: isMobile ? "130px" : "150px",
      zIndex: 80,
      scrollbarWidth: "none",
      msOverflowStyle: "none",
    },
    categoriaButton: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "8px",
      border: "none",
      background: "none",
      cursor: "pointer",
      minWidth: isMobile ? "80px" : "90px",
      padding: "12px 8px",
      borderRadius: "16px",
      transition: "all 0.3s ease",
    },
    categoriaIcon: { fontSize: isMobile ? "24px" : "28px" },
    categoriaNome: {
      fontSize: isMobile ? "12px" : "13px",
      fontWeight: "800",
      color: "#64748B",
      textTransform: "capitalize",
      textAlign: "center",
    },
    categoriaNomeAtiva: { color: "#10B981" },
    categoriaButtonAtiva: {
      background: "#F0FDF4",
      border: "2px solid #10B981",
      transform: "translateY(-2px)",
    },

    shell: {
      display: isMobile ? "block" : "grid",
      gridTemplateColumns: isMobile ? "1fr" : "280px 1fr",
      gap: isMobile ? "0" : "24px",
      padding: isMobile ? "0" : "24px",
      paddingBottom: isMobile ? "140px" : "120px",
    },

    desktopSidebar: {
      display: isMobile ? "none" : "block",
      background: "white",
      borderRadius: "20px",
      padding: "24px",
      border: "1px solid #E2E8F0",
      height: "fit-content",
      position: "sticky",
      top: "200px",
      maxHeight: "calc(100vh - 220px)",
      overflowY: "auto",
      boxShadow: "0 8px 25px rgba(0,0,0,0.05)",
    },
    sideTitle: {
      margin: "0 0 20px 0",
      fontSize: "18px",
      fontWeight: "900",
      color: "#0F3460",
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    sideCatBtn: (active) => ({
      width: "100%",
      textAlign: "left",
      padding: "16px 20px",
      borderRadius: "16px",
      border: "2px solid #E2E8F0",
      background: active ? "#F0FDF4" : "white",
      cursor: "pointer",
      fontWeight: 800,
      color: active ? "#065F46" : "#0F3460",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "12px",
      transition: "all 0.3s ease",
    }),

    cardapioContainer: {
      padding: isMobile ? "16px 16px 140px" : "0",
      backgroundColor: isMobile ? "#F8FAFC" : "transparent",
    },
    categoriaSection: {
      marginBottom: "32px",
      backgroundColor: isMobile ? "white" : "transparent",
      borderRadius: isMobile ? "20px" : "0",
      padding: isMobile ? "20px" : "0",
      boxShadow: isMobile ? "0 8px 25px rgba(0,0,0,0.08)" : "none",
    },
    categoriaHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "16px 0",
      borderBottom: "2px solid #F1F5F9",
      marginBottom: "20px",
      cursor: "pointer",
    },
    categoriaTitle: {
      margin: 0,
      fontSize: isMobile ? "20px" : "22px",
      color: "#0F3460",
      display: "flex",
      alignItems: "center",
      gap: "12px",
      textTransform: "capitalize",
      fontWeight: "900",
    },
    categoriaCount: {
      fontSize: "14px",
      color: "#94A3B8",
      fontWeight: "normal",
      backgroundColor: "#F1F5F9",
      padding: "6px 12px",
      borderRadius: "20px",
    },

    itensGrid: {
      display: "grid",
      gridTemplateColumns: isMobile ? "1fr" : isTablet ? "repeat(2, 1fr)" : "repeat(3, 1fr)",
      gap: isMobile ? "20px" : "24px",
    },
    itensList: {
      display: "flex",
      flexDirection: "column",
      gap: "16px",
    },

    itemCard: {
      backgroundColor: "white",
      borderRadius: "20px",
      overflow: "hidden",
      boxShadow: "0 8px 25px rgba(0,0,0,0.08)",
      border: "1px solid #F1F5F9",
      transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
      position: "relative",
    },
    itemImageContainer: {
      width: "100%",
      height: isMobile ? "180px" : "200px",
      overflow: "hidden",
      backgroundColor: "#F1F5F9",
      position: "relative",
    },
    itemImage: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
      transition: "transform 0.6s ease",
    },
    favoritoButton: {
      position: "absolute",
      top: "12px",
      right: "12px",
      background: "rgba(255,255,255,0.9)",
      border: "none",
      borderRadius: "50%",
      width: "40px",
      height: "40px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      zIndex: 2,
      transition: "all 0.3s ease",
    },
    itemPromoBadge: {
      position: "absolute",
      top: "12px",
      left: "12px",
      background: "linear-gradient(135deg, #EF4444 0%, #DC2626 100%)",
      color: "white",
      padding: "6px 12px",
      borderRadius: "20px",
      fontSize: "11px",
      fontWeight: "900",
      zIndex: 2,
      display: "flex",
      alignItems: "center",
      gap: "6px",
    },
    itemContent: {
      padding: isMobile ? "20px" : "24px",
    },
    itemName: {
      margin: "0 0 8px 0",
      fontSize: isMobile ? "16px" : "18px",
      fontWeight: "900",
      color: "#0F3460",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    itemDescription: {
      margin: "0 0 16px 0",
      fontSize: isMobile ? "13px" : "14px",
      color: "#64748B",
      display: "-webkit-box",
      WebkitLineClamp: 2,
      WebkitBoxOrient: "vertical",
      overflow: "hidden",
      height: isMobile ? "40px" : "44px",
      lineHeight: "1.5",
    },
    itemFooter: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "16px",
    },
    itemPrice: {
      fontSize: isMobile ? "18px" : "20px",
      fontWeight: "900",
      color: "#10B981",
    },
    addButton: {
      border: "none",
      borderRadius: "12px",
      padding: isMobile ? "10px 16px" : "12px 20px",
      color: "white",
      fontSize: isMobile ? "13px" : "14px",
      fontWeight: "900",
      cursor: "pointer",
      whiteSpace: "nowrap",
      transition: "all 0.3s ease",
      background: "linear-gradient(135deg, #10B981 0%, #059669 100%)",
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },

    loadingContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "80px 20px",
      textAlign: "center",
    },
    loadingSpinner: {
      width: "60px",
      height: "60px",
      border: "3px solid #F1F5F9",
      borderTopColor: "#10B981",
      borderRadius: "50%",
      animation: "spin 1s linear infinite",
      marginBottom: "20px",
    },

    filtrosSidebar: {
      position: "fixed",
      top: 0,
      right: showFilters ? "0" : "-100%",
      width: isMobile ? "90%" : "380px",
      height: "100vh",
      backgroundColor: "white",
      boxShadow: "-15px 0 40px rgba(0,0,0,0.15)",
      zIndex: 2000,
      transition: "right 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
      padding: "24px",
      overflowY: "auto",
    },
    filtroHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "24px",
      paddingBottom: "20px",
      borderBottom: "2px solid #F1F5F9",
    },
    filtroTitle: {
      margin: 0,
      fontSize: "24px",
      color: "#0F3460",
      fontWeight: "900",
      display: "flex",
      alignItems: "center",
      gap: "12px",
    },
    closeBtn: {
      background: "#F1F5F9",
      border: "none",
      borderRadius: "50%",
      padding: "10px",
      cursor: "pointer",
      transition: "background-color 0.2s ease",
      flexShrink: 0,
    },
    filtroGroup: { marginBottom: "30px" },
    filtroLabel: {
      display: "block",
      marginBottom: "12px",
      fontSize: "15px",
      fontWeight: "800",
      color: "#4A5568",
    },
    filtroSelect: {
      width: "100%",
      padding: "14px 16px",
      borderRadius: "12px",
      border: "2px solid #E2E8F0",
      fontSize: "15px",
      backgroundColor: "#F8FAFC",
      color: "#4A5568",
      outline: "none",
    },
    filtroRange: { display: "flex", gap: "12px", alignItems: "center" },
    filtroInput: {
      flex: 1,
      padding: "12px 16px",
      borderRadius: "10px",
      border: "2px solid #E2E8F0",
      fontSize: "15px",
      backgroundColor: "#F8FAFC",
      outline: "none",
    },

    carrinhoFlutuante: {
      position: "fixed",
      bottom: isMobile ? "20px" : "24px",
      right: isMobile ? "5%" : "24px",
      left: isMobile ? "5%" : "auto",
      width: isMobile ? "90%" : isTablet ? "340px" : "380px",
      background: "linear-gradient(135deg, #0F3460 0%, #1E40AF 100%)",
      padding: isMobile ? "20px" : "24px",
      borderRadius: "24px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      color: "white",
      boxShadow: "0 15px 40px rgba(15, 52, 96, 0.3)",
      zIndex: 1500,
    },
    carrinhoAction: {
      background: "linear-gradient(135deg, #10B981 0%, #059669 100%)",
      color: "white",
      border: "none",
      borderRadius: "14px",
      padding: isMobile ? "12px 20px" : "14px 24px",
      fontWeight: "900",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: "10px",
      whiteSpace: "nowrap",
      fontSize: isMobile ? "15px" : "16px",
      boxShadow: "0 4px 15px rgba(16, 185, 129, 0.3)",
    },

    // Modal
    modalOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.7)",
      display: "flex",
      alignItems: isMobile ? "flex-end" : "center",
      justifyContent: "center",
      zIndex: 3000,
      padding: isMobile ? "0" : "20px",
      backdropFilter: "blur(5px)",
    },
    modalContent: {
      backgroundColor: "white",
      width: isMobile ? "100%" : "min(800px, 100%)",
      borderTopLeftRadius: isMobile ? "32px" : "24px",
      borderTopRightRadius: isMobile ? "32px" : "24px",
      borderRadius: isMobile ? "32px 32px 0 0" : "24px",
      padding: isMobile ? "24px" : "32px",
      maxHeight: isMobile ? "85vh" : "90vh",
      overflowY: "auto",
      boxShadow: "0 25px 50px rgba(0,0,0,0.25)",
    },
    modalHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: "16px",
      marginBottom: "24px",
    },
    modalTitle: {
      margin: 0,
      fontSize: isMobile ? "22px" : "26px",
      fontWeight: "900",
      color: "#0F3460",
    },
    modalSub: {
      margin: "8px 0 0 0",
      fontSize: isMobile ? "14px" : "16px",
      color: "#64748B",
    },

    grupoBox: {
      marginTop: "24px",
      paddingTop: "20px",
      borderTop: "2px solid #F1F5F9",
    },
    grupoNome: {
      margin: 0,
      fontSize: isMobile ? "16px" : "18px",
      fontWeight: "900",
      color: "#0F3460",
    },
    grupoLimites: {
      margin: "8px 0 20px 0",
      fontSize: isMobile ? "13px" : "14px",
      color: "#64748B",
    },
    opcaoCard: (selected) => ({
      display: "flex",
      alignItems: "center",
      gap: "16px",
      padding: isMobile ? "16px" : "20px",
      borderRadius: "16px",
      border: `3px solid ${selected ? "#10B981" : "#E2E8F0"}`,
      background: selected ? "#F0FDF4" : "white",
      cursor: "pointer",
      marginBottom: "12px",
      transition: "all 0.3s ease",
    }),
    opcaoImg: {
      width: isMobile ? "60px" : "70px",
      height: isMobile ? "60px" : "70px",
      borderRadius: "12px",
      objectFit: "cover",
      background: "#F1F5F9",
      flexShrink: 0,
    },
    checkboxCircle: {
      width: "28px",
      height: "28px",
      borderRadius: "50%",
      border: "3px solid #CBD5E1",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
      transition: "all 0.2s ease",
    },
    checkboxActive: { backgroundColor: "#10B981", borderColor: "#10B981" },

    btnConfirmar: (enabled) => ({
      width: "100%",
      padding: isMobile ? "18px" : "22px",
      borderRadius: "16px",
      border: "none",
      background: enabled
        ? "linear-gradient(135deg, #10B981 0%, #059669 100%)"
        : "#CBD5E0",
      color: "white",
      fontWeight: "900",
      fontSize: isMobile ? "16px" : "18px",
      marginTop: "24px",
      cursor: enabled ? "pointer" : "not-allowed",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "12px",
      boxShadow: enabled ? "0 4px 20px rgba(16, 185, 129, 0.3)" : "none",
    }),
  };
}
